# Generated by Django 5.2.8 on 2025-11-23 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('division', models.CharField(max_length=100)),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ASSAULT', 'Assault'), ('ROBBERY', 'Robbery'), ('HOMICIDE', 'Homicide'), ('OTHER', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
